setup:
  module: Compound
  class: LiquidMover.LiquidMoverSetup
  settings:
    tip_approach_height: 20
    component_config:
      mover: 
        module: Move
        class: Jointed.Dobot.M1Pro
        settings:
          ip_address: '192.109.209.21'
          home_coordinates: {'tuple': [300,0,200]}
          home_orientation: {'tuple': [10,0,0]}
          orientate_matrix: {'array': [[0.015426152906427654,0.9998810098239228,0],[-0.9998810098239228,0.015426152906427654,0],[0,0,1]]}
          translate_vector: {'array': [-274.51943236148054,330.24797381150586,283.5]}
          scale: 1
          implement_offset: {'tuple': [0,0,-243]}
      liquid: 
        module: Transfer
        class: Liquid.Sartorius.Sartorius
        settings:
          port: 'COM8'
          channel: 1
          offset: [0,0,0]

balance:
  module: Measure
  class: Physical.MassBalance
  settings:
    port: 'COM4'
    calibration_factor: 6.862879436681862

SHORTCUTS:
  mover: setup.mover
  liquid: setup.liquid